[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown']
hook_source = '''
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescriptreact']

[[plugins]]
repo = 'ianks/vim-tsx'
on_ft = ['typescript', 'typescriptreact']
